### ISSUE TITLE
Any plans to support noetic ROS

### ISSUE THREAD

**Issue by chrissunny94** [boschresearch/ros1_tracetools#6]
I was trying this today 
I am not able to launch anything .

```

trace_ws/src/ros_comm/tools/roslaunch/src/roslaunch/parent.py", line 273, in start
    self.logger.info("starting roslaunch parent run")
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by christophebedard** [comment]
I don't think any more development work is going to be done on this repo/project.

The call stack and error message don't seem to be related to the code in this repo though.

**Comment by chrissunny94** [comment]
Oh i see . Thats sad that support on this project is stopped   . 

The issue comes with the **ros_comm layer** that is modified , **not being adapted for ROS noetic** . I think its to do with Python3 changes .

**Comment by christophebedard** [comment]
The efforts moved to ROS 2 here: https://gitlab.com/ros-tracing/ros2_tracing

> The issue comes with the **ros_comm layer** that is modified , **not being adapted for ROS noetic** . I think its to do with Python3 changes .

ah yes you're right! If you want to get it working on Noetic, you'll need to rebase the modified branch or cherry-pick the commits onto the `noetic` ros_comm branch.
